name: Test
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [on-sdk-update]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        opt: [O0, O3, Os, Oz]
      fail-fast: false

    steps:
      - name: Install build dependencies.
        run: |
          sudo apt-get install cmake ninja-build
          python -m pip install git+https://github.com/llvm/llvm-project.git#subdirectory=llvm/utils/lit
      - name: Check out the test suite.
        uses: actions/checkout@v2
      - name: Fetch the latest prerelease SDK.
        run: |
          curl -LO https://github.com/llvm-mos/llvm-mos-sdk/releases/download/linux-prerelease/llvm-mos.tar.xz
          tar -xvf llvm-mos.tar.xz
      - name: Build the test suite.
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_C_COMPILER=$GITHUB_WORKSPACE/llvm-mos/bin/mos-sim-clang \
            -DCMAKE_CXX_COMPILER=$GITHUB_WORKSPACE/llvm-mos/bin/mos-sim-clang++ \
            -DARCH=MOS \
            -DTEST_SUITE_SUBDIRS=SingleSource/ \
            -DTEST_SUITE_RUN_UNDER=$GITHUB_WORKSPACE/llvm-mos/bin/mos-sim \
            -DTEST_SUITE_USER_MODE_EMULATION=yes \
            -DTEST_SUITE_LLVM_SIZE="" \
            -DCMAKE_STRIP="" \
            -G Ninja \
            -C../cmake/caches/${{ matrix.opt }}.cmake \
            ..
          ninja
      - name: Run the test suite.
        run: |
          cd build
          lit .
